[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "7.0.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "~3.3.2"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "~0.6.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/google/jsonapi"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.1"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.6.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/ory/hydra"
  version = "v1.0.0-rc.6+oryOS.10"
